### ISSUE TITLE
GitPrint ne fonctionne pas

### ISSUE THREAD

**Issue by fsailly** [holacracyone/Holacracy-Constitution-4.1-FRENCH#10]
Bonjour et bravo pour votre travail !
J'aurais aimé imprimer la constitution pour la lire tranquillement au soleil, mais malheureusement la génération du fichier ne fonctionne pas (gitprint dispo dans readme.md).
Pouvez-vous y jeter un oeil ?
Merci, bonne journée

**Comment by LouisChiquet** [comment]
Bonjour @fsailly,

Pour imprimer la Constitution, je vous invite à regarder ce lien ci, où vous trouverez un bouton “Télécharger la Constitution en PDF” afin de pouvoir pour l'imprimer et l'apprécier comme il se doit en ce bel été : https://igipartners.com/constitution-holacracy

Bonne lecture,
Belle soirée à vous,

**Comment by oliviercp** [comment]
@fsailly malheureusement je pense que c'est un problème avec GitPrint...

**Comment by fsailly** [comment]
Merci @LouisChiquet et @ocompagne  !
Très bonne journée.

**Comment by bernardmariechiquet** [comment]
@fsailly Je me permets donc de fermer cette issue, il semble que vous ayez ce dont vous aviez besoin.
Si ce n'est pas le cas, faites le moi savoir. 
Bien à vous.
