### ISSUE TITLE
"Impact a Domain" -> impacter? influencer? affecter?

### ISSUE THREAD

**Issue by oliviercp** [holacracyone/Holacracy-Constitution-4.1-FRENCH#5]
Henriett a suggere de traduire "to impact" par "influencer" plutot que "impacter" (pull request #4). En effet, "impacter" n'est pas un mot francais, bien qu'il soit sans doute utilise de plus en plus souvent dans le business. Mais ca reste un anglicisme, donc une meilleure traduction est la bienvenue.

Je pense qu' "influencer" n'est pas bien adapte car il est trop vague et passif — il y a plein de facons d'influencer quelque chose. A la place, je propose "affecter", qui porte un peu plus la notion de controle qui est voulu dans la constitution.

Je serais curieux d'avoir votre feedback.

**Comment by bernardmariechiquet** [comment]
"impacter" est un mot français - j'ai moi aussi chercher d'autres mots mais je n'ai pas trouvé mieux. "Influencer" ne correspond en terme de sens à ce dont il s'agit ici. Je reste ouvert naturellement à d'autres mots.

**Comment by oliviercp** [comment]
Affecter?

**Comment by romain-inxl** [comment]
Impacter est une création récente à partir de l'anglais, voici ce qu'en dit l'Académie : "C’est à tort qu’on a, en s’inspirant de l’anglais, créé la forme verbale Impacter pour dire « avoir des conséquences, des effets, de l’influence sur quelque chose »." (http://www.academie-francaise.fr/impacter), par ailleurs, il est employé dans un cadre habituellement business et le Larousse précise : "Familier. Avoir un impact, une incidence, généralement négatifs, sur“. Faute de grives ça passe, mais je pense qu'il est préférable de trouver un mot qui n'ait pas de connotation négative et respecte le sens.

Affecter me semble trop faible. Toucher est courant. Il est parfois préférable de changer toute la tournure d'une phrase plutôt que de traduire mot à mot. Il me semble que "agir sur" a tout ce qu'il faut. "Les Rôles peuvent agir sur les Domaines du Cercle".

**Comment by bernardmariechiquet** [comment]
@romain-inxl Je trouve cette proposition intéressante, cela convient bien dans le cas ou le domaine est une fonction ou même une propriété (agir sur une fonction), elle me parait cependant moins adaptée par exemple dans le cas ou le domaine est un processus. Du coup en regardant le lien http://www.academie-francaise.fr/impacter, je vois le mot *affecter* qui me plairait plus s'il n'y avait la confusion avec le verbe affecter utilisé dans l'expression "affecter des rôles".

**Comment by romain-inxl** [comment]
À ce moment-là, pourrait-on imaginer utiliser "attribuer" pour l'expression "attribuer des rôles" ? Ce qui permet de ré-utiliser "affecter" pour ce sens de "avoir un effet sur" ?

**Comment by LouisChiquet** [comment]
Impacter peut être positif, “j'ai un impact sur la société”, c'est positif. Mais reste familier effectivement.
J'aime l'idée d'affecter, mais cela aurait un “impact” comme dit sur l'affectation des rôles. C'est pourquoi j'opterais pour “influer”, ce qui permettrais de changer juste “impacter” sans changer la tournure des phrases. @bernardmariechiquet ?

**Comment by margauxchiquet** [comment]
@bernardmariechiquet Tu en es où sur ce sujet ? J'aime bien ce qu'a mis Romain car “attribuer les rôles” c'est pas mal.

**Comment by bernardmariechiquet** [comment]
@margauxchiquet Oui, je n'ai pas de souci pour remplacer "affecter les rôles" par "attribuer les rôles", même si je ne vois pas beaucoup de valeur ajoutée à le faire, je n'ai pas d'objection.
Je comprends que cela permetrrait de remplacer "impacter un Domaine" par "affecter un Domaine" ce sur quoi je n'ai pas d'objection. 
Mais ce n'est pas si simple - il y l'expression "avoir un impact concret" qui me semble approprié, que je vois pas l'intérêt de changer. Je vais donc regarder à modifier "impacter" par "affecter".

**Comment by LouisChiquet** [comment]
Je serais contre. Article [1.4](https://github.com/holacracyone/Holacracy-Constitution-4.1-FRENCH/blob/master/Constitution-Holacracy.md#13-autorité-daction) “_Toutefois, vous ne pouvez pas exercer de contrôle ou **avoir un impact concret** sur un Domaine détenu par un autre Rôle ou une autre entité souveraine, sauf si vous y êtes autorisé. L’autorité conférée par le présent paragraphe est par ailleurs limitée par les dispositions de la Section 2.1.3._”.
Tu changes par quoi ? “_Avoir un effet concret_” ? C'est pourquoi je mettrais influer, et donc avoir une “_influence concrète_”, définition du Larousse “_Action, généralement continue, qu'exerce quelque chose sur quelque chose ou sur quelqu'un_”.
D'ailleurs, au vu du nombre d'Anglicisme en langue Française (je crois qu'il n'y a pas de problème pour dire Internet), je me demande si “_impact_” et “_impacter_” ne pourrait pas rester tel quel, malgré les définitions et commentaires de l'Académie (sachant que le mot/marque Holacracy n'est pas reconnu, et si on devait le traduire par exemple ça serait Holacratie).

**Comment by oliviercp** [comment]
Comme cette "issue" est toujours ouverte, je me permets d'ajouter qu'on a probablement a faire ici a une difference entre le francais de France et le francais du Canada. Les canadiens sont beaucoup plus sensibles aux anglicismes que les francais.

**Comment by romain-inxl** [comment]
En relisant tout cela, il me semble que "avoir un impact concret" était auparavant "impacter", ce qui posait problème (le verbe n'est pas français, mais le nom oui) et a ensuite été modifié. Je reste sur les nuances "affecter" et "attribuer" mais sans plus de force que cela. Dans mon souvenir, ce qui était dérangeant était surtout l'utilisation du verbe "impacter" (cf. mon premier message)… qu n'a plus lieu d'être semble-t-il.

**Comment by bernardmariechiquet** [comment]
@romain-inxl J'ai bien pris en compte le remplacement du verne "impacter" par "affecter".
@ocompagne Oui, c'est vrai, je vais vérifier avec des clients Québécois que j'accompagne.
Je pars donc sur le remplacement de "Impacter un Domaine" par "Affecter un Domaine" et le remplacement de "Affecter un Rôle" par "Attribuer un Rôle".
Je vais donc fermer cette issue et si quelqu'un souhaite aller plus loin, je l'invite à en ouvrir une autre.
