### ISSUE TITLE
Feedback from a GlassFrog client 

### ISSUE THREAD

**Issue by kalliekendle** [holacracyone/Holacracy-Constitution-4.1-FRENCH#8]
Bernard,   hello.  Margaux asked to have such translation feedback posted here so I am doing so myself to protect the client's privacy.   
I am looking for a fairly generic explanation that I can give to this client and others in terms of the choice of translations for the following 3 terms: 
Lead Link -> in French "premier lien" -> literal translation back in English "First Link"
Rep Link -> in French "second lien" ->  literal Translation back in English "Second Link"
Sub-circle : in French "sous-cercle" -> litteral translation back in English "under-circle".

The client indicated that these have a strong concept of hierarchy, which does not appear to them to align well with Holacracy practices.
Thanks!

**Comment by bernardmariechiquet** [comment]
​Hi Kallie,

Thank you for your comment. As ​we are on the french Holacracy constitution, I will answer in french directly:

Préambule à ma réponse : nous pratiquons Holacracy et accompagnement les entreprises dans cette transformation depuis plus de 8 ans et avons choisi ces mots au tout début avec notre compréhension de Holacracy à l'époque et les remettons en cause régulièrement pour s'assurer de leur justesse. Ils ont été validé par HolacracyOne en tant que traduction officielle. Ce n'est pas simplement de la traduction pure, c'est une localisation pour s'adapter au marché francophone et à la culture francophone, qui est très différente de la culture américaine. Nous avons consulté nos clients pour cela et avons intégré tout feedback. Nous pourrions évidemment les changer même si cela aurait un fort impact mais je vais d'abord tenter d'expliquer l'intention derrière ce choix précis et murement réfléchi. Si vous souhaitez ajouter d'autres éléments pour argumenter, je suis ouvert :)

1/ Pourquoi traduire “Lead Link” par “Premier Lien” ?
La traduction de Lead Link basique serait “Lien Leader”. Le terme “Leader”, anglais, est connoté, c'est celui qui mène, qui lead. S'il y a un lien leader, alors je ne suis pas leader moi en tant que simple collaborateur avec des rôles dans ce Cercle. C'est pourquoi, nous avons préféré un terme plus neutre “Premier Lien”, comme il y a deux liens : le premier et le deuxième, sans notion de hiérarchie quelconque. 

2/ Pourquoi traduire “Rep Link” par “Second Lien” ?
La traduction de Rep Link basique serait “Lien Représentant” ou “Lien Représentatif”, ce qui induirait qu'il représente quelque chose et l'interprétation est souvent qu'il représente les personnes alors que pas du tout. Le terme portant à confusion, nous avons préféré quelque chose de plus neutre. Le Premier Lien est le lien qui descend du haut vers le bas et le Second Lien du bas vers le haut. Il n'y en a pas un mieux que l'autre, ce sont juste deux liens et aucun n'est subordonné à l'autre.

3/ Pourquoi traduire “Sub-Circle” par “Sous-Cercle” ?
Je pense que la traduction est juste et la signification la même qu'en anglais. En avez-vous une autre à proposer ? C'est bien hiérarchique, c'est bien un Sous-Cercle du Cercle plus large. Y'a une hiérarchie de Cercles et de rôles en Holacracy, c'est ça l'holarchie, de même que dans votre corps humain, vous avez une hiérarchie de latitude croissante : atome - molécule - cellule - organes - etc.. 

En complément : Holacracy, ce n'est pas l'absence de hiérarchie, au contraire ! C'est souvent une mauvaise interprétation au début.
Pour LL/PL et RL/SL : Même Brian n'est pas 100% à l'aise avec les termes anglais mais il n'a pas trouvé mieux. Il y a du bon et du mauvais dans les deux versions. Après, ce sont juste des mots et ce qui compte c'est le sens qu'on leur donne lorsqu'on met en place Holacracy. C'est une grosse transformation avec une déhiérarchisation importante et dans la tête des collaborateurs, que ce soit LL ou PL, ils penseront “= manager”. L'enjeu ce ne sont pas tant les mots puisque ce sont de nouveaux mots avec des définitions précises mais plutôt la transformation et déhiérarchisation profonde de l'organisation, ce que nous faisons lorsque nous accompagnons nos clients.

Au plaisir de vous lire,

**Comment by kalliekendle** [comment]
Bernard Marie,
Very much appreciate your considered response.  I will pass this along to our client and will update you if there are more questions.  Thanks again!  Kallie

**Comment by romain-inxl** [comment]
Pour info, nous parlons souvent de Lien Garant et Lien Remontant qui, s'ils peuvent être a priori "moches", me semblent bien coller à la réalité ainsi qu'au commentaire de Bernard Marie. Par ailleurs, Lien Garant a l'avantage (l'air de rien) de ne pas attirer l'envie des ex-managers qui se cherchent encore un titre qu'ils trouvent dans "Premier" de Premier Lien. À partir du moment où on parle de premier et de second, il y a de facto une notion hiérarchique au moins dans les termes (puisque dans le concept) et je ne vois pas comment l'enlever facilement des esprits.

Lien Garant (on aurait pu dire "gérant" aussi mais c'est moins exact) car il est garant de la bonne fin confiée à son Cercle, tant dans la stratégie et les missions que dans les ressources. Pour Lien Remontant, je pense que toute explication est superflue, le terme va de soi (et cette dénomination n'indique pas de représentation de personnes mais plutôt de tensions).

**Comment by margauxchiquet** [comment]
Hello,

Je réagis sur ce post intéressant ! Merci pour les idées.
Personnellement, je trouve que les termes anglais sont mal choisis aussi donc difficile d'avoir une bonne traduction. Premier Lien et Second Lien, ça fait neutre et nécessite des explications, on peut pas interpréter.
Je trouve que “lien remontant” et “lien garant” sont des bonnes idées mais ne traduisent pas toute la subtilité des rôles malheureusement... Difficile de trouver quelque chose !

**Comment by margauxchiquet** [comment]
Well, on devra de toute façon le changer avec la nouvelle version : https://github.com/holacracyone/Holacracy-Constitution/issues/198#event-1692740058

**Comment by LouisChiquet** [comment]
Brian a fait ses commentaires sur le sujet, le nom va de toute façon changer en Circle Lead (qui peut être remis sur la table, de même que Rep Link), donc cela ne sert pas trop selon moi de divaguer sur le terme Français si cela change : https://github.com/holacracyone/Holacracy-Constitution/issues/198#issuecomment-398978154

**Comment by bernardmariechiquet** [comment]
J'envisage de changer ces noms de 1er Lien et 2nd Lien pour de nombreuses raisons et le ferais avec la version 5.0. Les mots anglais Lead Link et Rep Link ont leurs inconvénients, ce qui nous a faut choisir Premier Lien et Second Lien à l'époque. Et ces derniers ont leurs avantages et leurs inconvénients.
@romain-inxl je ne suis pas à l'aise avec le mot Lien Garant même si je comprend l'intention qui est deerrière et ce pour plusieurs raisons. Le rôle Lead Link est bien plus qu'un Lien, c'est avant tout un rôle avec des redevabilités, je me dirrige donc vers un mot qui ne contient pas le mot "Lien".
Je vais fermer cette issue et si quelqu'un souhaite poursuivre cet échange, je l'invite à ouvrir une nouvelle issue.
